### ISSUE TITLE
Step 1 .m files seem encrypted and messed up

### ISSUE THREAD

**Issue by readypeng** [XhxngX2/intekey-crack#1]
> Open Matlab 2015b. Forward to the folder of step 1. change the variable of crack path. Click run script, the step2 will be called in step1 .m file using "system" command.

But all 3 .m files in the **Step_1** folder seem messed up. Here is how it looks.

![image](https://user-images.githubusercontent.com/38313898/82520034-bc2fdc00-9b55-11ea-9cc9-2675e551dcfd.png)

Could you be kind enough to re-commit the unencrypted files?

**Comment by XhxngX2** [comment]
Do you really need those files?  for this repository, only those .c .h .asm I used is in my crack plan.

**Comment by readypeng** [comment]
Sorry, I am a little bit confused... Do you mean we don't need files in Step_1 folder to do the cracking? So how should we perform the crack? Thanks in advance!

**Comment by XhxngX2** [comment]
hey! 
The whole process is like:
1. use permitted software to read the content of the old encrypted file.
2. then permitted software will write the contents to an untracked format.
3. use unpermitted software to reformat the file.

e.g  HelloWorld.c. 
This file is tracked by Intekey software, we can use permitted software like MatLab to read the content in .c file.
then write to another new file, in this case, will write to Helloworld.cCrack.
then use a python script to name .cCrack file to .c file. 
now we get the free .c file.

note, do not open the cracked c file. for Intekey will encrypt those files in the tracklist once you open them with permitted software. 

In my last reply, I asked whether you need the .m files. is because I'm a software engineer. I only care about those source code file formats.  in this version of code, only .c .h .asm is supported, some of you may want to crack .dwg .xlsx files, etc. 
I will update unencrypted .m files together with python source codes later this afternoon.




__

**Comment by XhxngX2** [comment]
fixed
